layout_spectrum: 0.4749103
typography_spectrum: 0.5203106
color:
  saturation: 0.9504181
  brandStrength: 0.819632
  lightness: 0.07347666
  rhythmicContrast: 0.8751493
name: 'Fork In Cheese Productions '
